export const portfolioItems = [
  {
    id: 1,
    title: "Modern Architectural House Model",
    category: "Architecture",
    tags: ["architecture", "residential", "models"],
    image: "/images/3d-house.jpg",
    description:
      "A detailed architectural model of a modern minimalist house with multiple levels and open spaces. Perfect for client presentations and design visualization.",
    client: "Architectural Design Studio",
    material: "White PLA",
    printTime: "24 hours",
  },
  {
    id: 2,
    title: "Functional Robotic Arm",
    category: "Engineering",
    tags: ["engineering", "robotics", "functional"],
    image: "/images/robotic-arm.jpg",
    description:
      "A fully functional 3D printed robotic arm with servo motors and electronic components. Features a gripper mechanism and multiple points of articulation.",
    client: "Engineering Research Lab",
    material: "Red & White PLA, Electronic Components",
    printTime: "16 hours",
  },
  {
    id: 3,
    title: "Lord Ganesha Figurine",
    category: "Art & Gifts",
    tags: ["art", "religious", "gifts"],
    image: "/images/lord-ganesha.png",
    description:
      "A detailed small scale model of the printed devotee lord Ghanesha printed with high quality filament and durable in strength",
    client: "Sandeep Mishra",
    material: "PLA, Blue",
    printTime: "40 Minutes",
  },
  {
    id: 4,
    title: "Gradient Phone Stand",
    category: "Tools",
    tags: ["tools", "accessories", "functional"],
    image: "/images/phone-stand.webp",
    description:
      "A stylish phone stand with gradient coloring, designed for optimal viewing angles and cable management.",
    client: "Tech Accessories Shop",
    material: "PLA with Gradient Effect",
    printTime: "4 hours",
  },
  {
    id: 5,
    title: "Miniature Boat Model",
    category: "Education",
    tags: ["education", "toys", "models"],
    image: "/images/boat.jpg",
    description:
      "Detailed model of a boat suitable for decoration and gifting purposes and also available for architectural purposes.",
    client: "Suman Bhati ",
    material: "White PLA",
    printTime: "30 Minutes",
  },
  {
    id: 6,
    title: "Articulated Dinosaur",
    category: "Toys & Games",
    tags: ["toys", "education", "gifts"],
    image: "/images/dinosaur.jpg",
    description:
      "A cheerful model of a dino, expressing about the emotion of Joy optimal for giftings and décor purposes",
    client: "Mandeep Singh",
    material: "Blue and White PLA",
    printTime: "1.5 hours",
  },
  {
    id: 7,
    title: "Spider Model",
    category: "Education",
    tags: ["education", "science", "biology"],
    image: "/images/spider.jpg",
    description:
      "Model of a spider describing about the texture and the physical features of it best for educational purposes and demonstration",
    client: "Jatin Bansal",
    material: "White PLA",
    printTime: "25 Minutes",
  },
]
